ViewsAndControllers.PL/Controllers/QuestionnaireController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using ViewsAndControllers.BLL.DTO;
using ViewsAndControllers.BLL.Interfaces;
using ViewsAndControllers.PL.Models;

namespace ViewsAndControllers.PL.Controllers
{
    public class QuestionnaireController : Controller
    {
        private IUserBookService userBookService;
        private IBookService bookService;

        public QuestionnaireController(IUserBookService service, IBookService bookServ)
        {
            userBookService = service;
            bookService = bookServ;
        }        

        public ActionResult Questionnaire()
        {
            UserBook userBook = new UserBook();
            ViewBag.favbook = "1";
            var bookDTOs = bookService.GetBooks();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<BookDTO, Book>()).CreateMapper();
            var books = mapper.Map<IEnumerable<BookDTO>, List<Book>>(bookDTOs);
            userBook.Books = books;
            return View(userBook);
        }

        [HttpPost]
        public ActionResult Questionnaire(UserBook ui)
        {
            if (String.IsNullOrEmpty(ui.UserName) || String.IsNullOrEmpty(ui.City) ||
                String.IsNullOrEmpty(ui.RadioAns))
            {
                if (ui.Books.All(c => c.CheckAns == false))
                {
                    ModelState.AddModelError("CheckAns", "Choose your read books");
                }
                return View(ui);
            }

            if (ui.Books.All(c => c.CheckAns == false))
            {
                ModelState.AddModelError("CheckAns", "Choose your read books");
                return View(ui);
            }


            StringBuilder sb = new StringBuilder();
            foreach (var i in ui.Books)
            {
                if (i.CheckAns)
                {
                    sb.Append(i.Name + ", ");
                }
            }

            ViewBag.SelectBook = sb.ToString().Remove(sb.Length - 2);


            return View("UserInfo", ui);
        }
    }
}

ViewsAndControllers.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header class="container-fluid text-center  active" name="top">
        <h1><img src="~/Content/img/icon1.png" width="70" height="50" /> Library</h1>
    </header>

    <div class="container" style="width: 80%">
        <div class="col-lg-11">
            @RenderBody()
        </div>
        <div class="nav navbar-nav col-lg-1">
            <ul class="nav flex-column">
                <li>@Html.ActionLink("Головна", "Index", "Home")</li>
                <li>@Html.ActionLink("Гостьова", "Guest", "Guest")</li>
                <li>@Html.ActionLink("Анкета", "Questionnaire", "Questionnaire")</li>
            </ul>
        </div>



    </div>

    <hr />
    <footer class="container-fluid text-center">
        <a href="#top">Back to top of page</a>
        <p>&copy; Pavlo Pryima pashaprujma@gmail.com</p>
    </footer>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>